inherit: 
    - base.yaml

model:
    family: gpt2
    n_dims: 20
    n_embd: 256
    n_layer: 12
    n_head: 8
    n_positions: 101

training:
    task: linear_regression
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 50001
    curriculum:
        dims:
            end: 20
            inc: 1
            interval: 2000
            start: 5
        points:
            end: 71
            inc: 2
            interval: 2000
            start: 11
        
out_dir: ../models/linear_regression

wandb:
    name: "linear_regression_fixedcov_N70_test2"
